add_idl(ChannelSearchServiceIDL ChannelSearchService.idl ${IDL_DIRECTORY}/ChannelSearchSvcs/ChannelSearchService)

add_executable(ChannelSearchService
  ChannelMatcher.cpp
  ChannelSearchServiceMain.cpp
  ChannelSearchServiceImpl.cpp
)
target_link_libraries(ChannelSearchService
  PRIVATE
    AdServerCommonsXSD
    CORBACommons
    CampaignCommonsIDL
    CampaignServerIDL
    ChannelSearchServiceConfigXSD
    ChannelSearchServiceIDL
    ChannelServerGrpc
    ChannelServerIDL
    ChannelGrpcClient
    CorbaTypesIDL
    CORBAConfig
    ExpressionChannel
    ExpressionChannelIndex
    Generics
    GrpcBatch
    HTTP
    Logger
    ProcessControlIDL
    ProcessControlVars
    Sync
)
