add_library(ImprTrackFrontend SHARED
  ImprTrackFrontend.cpp
  RequestInfoFiller.cpp
)

target_link_libraries(ImprTrackFrontend
  Stream
  Geoip
  CORBACommons
  Polyglot
  Commons
  ChannelManagerControllerIDL
  UserInfoManagerControllerIDL
  UserInfoClusterControlIDL
  DomainParser
  StatInfoIDL
  BillStatInfoIDL
  CampaignServerIDL
  UserBindServerIDL
  UserBindContainer
  UserBindClient
  RequestMatchers
  FrontendStatistic
  UserIdController
  CommonModule
  CampaignManagerClient
  FeConfigXSD
  FCGI
)
