add_executable(InstantiateAdArgsTest
  InstantiateAdArgsTest.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/CampaignManagerCore.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/CreativeInstantiator.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/CreativeTextGenerator.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/ConfigManips.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/SelectCreative.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/CampaignSelector.cpp
  ${CMAKE_SOURCE_DIR}/CampaignSvcs/CampaignManager/BillingStateContainer.cpp
)

target_link_libraries(InstantiateAdArgsTest
  PRIVATE
    PkgConfig::Jemalloc
    CampaignConfigSource
    HTTP
    HttpServer
    CORBACommons
    Commons
    CORBAConfig
    AdServerCommonsXSD
    CampaignManagerConfigXSD
    CampaignCommonsIDL
    CampaignServerIDL
    CorbaTypesIDL
    ProcessControlIDL
    CampaignTypes
    ExpressionChannelIndex
    ExpressionChannel
    InstantiateAdArgs
    CreativeTemplateArgs
    CampaignConfig
    CampaignBillingAccount
    CampaignIndex
    DomainParser
    CampaignManagerLogger
    PassbackTemplate
    SecToken
    CTRProvider
    CTRProviderImplLib
    BidRateProvider
    DomainConfigXSD
    CampaignManagerGrpc
    BillingServerGrpcClient
    Generics
    Sync
)

target_include_directories(InstantiateAdArgsTest
  PRIVATE
    ${CMAKE_SOURCE_DIR}
    ${Protobuf_INCLUDE_DIRS}
)
