ADD_SUBDIRECTORY(ChannelAdmin)
ADD_SUBDIRECTORY(ChannelCommons)
ADD_SUBDIRECTORY(ChannelController)
ADD_SUBDIRECTORY(ChannelManagerController)
ADD_SUBDIRECTORY(ChannelServer)
ADD_SUBDIRECTORY(ChannelClient)
ADD_SUBDIRECTORY(ChannelAdmin2)
ADD_SUBDIRECTORY(DictionaryProvider)
ADD_SUBDIRECTORY(TriggerFilter)
