<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.adintelligence.net/xsd/AdServer/Configuration"
  xmlns="http://www.adintelligence.net/xsd/AdServer/Configuration"
  elementFormDefault="qualified"
  xml:lang="en"
  version="1.0">

  <xsd:annotation>
    <xsd:documentation>
      User Bind Controller2 Configuration File XML Schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="./UserBindController2AppType.xsd"/>

  <xsd:element name="userBindController2" type="UserBindController2ConfigType">
    <xsd:annotation>
      <xsd:documentation>
        UserBindController2 configuration.
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>

</xsd:schema>
