<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.adintelligence.net/xsd/AdServer/Configuration"
  xmlns="http://www.adintelligence.net/xsd/AdServer/Configuration"
  elementFormDefault="qualified"
  xml:lang="en"
  version="1.0">

  <xsd:annotation>
    <xsd:documentation>
      ChannelController Configuration File XML Schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="../AdServerCommons/AdServerCommons.xsd"/>

  <xsd:element name="AdConfiguration" type="AdConfigurationType"/>

  <xsd:complexType name="AdConfigurationType">
    <xsd:sequence>
      <xsd:element name="ChannelControllerConfig"
        type="ChannelControllerConfigType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ChannelControllerConfigType">
    <xsd:sequence>
      <xsd:element name="GrpcConfig" type="GrpcConfigType">
        <xsd:annotation>
          <xsd:documentation>
            GrpcConfig for service
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element name="ColoSettings"
        type="ChannelControllerColoSettingsType"/>

      <xsd:element name="ChannelSource"
        type="ChannelControllerSourceType"/>

      <xsd:element name="Logger" type="ErrorLoggerType">
        <xsd:annotation>
          <xsd:documentation>
            Error logger for ChannelController
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element name="ChannelServerGroup"
        type="ChannelServerGroupType"
        minOccurs="1"
        maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation>
            ChannelServer gRPC endpoint group
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>

    <xsd:attribute name="count_chunks"
      type="xsd:positiveInteger"
      use="required"/>
    <xsd:attribute name="pid_file"
      type="xsd:string"
      use="required"/>
  </xsd:complexType>

  <xsd:complexType name="ChannelControllerRegularSourceType">
    <xsd:sequence>
      <xsd:element name="CampaignServerCorbaRef" type="MultiCorbaObjectRefType"/>
      <xsd:element name="PGConnection" type="PGConnectionType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ChannelControllerSourceType">
    <xsd:choice>
      <xsd:element name="RegularSource"
        type="ChannelControllerRegularSourceType"/>
      <xsd:element name="ProxySource"
        type="ChannelControllerProxySourceType"/>
    </xsd:choice>
    <xsd:attribute name="local_groups" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="ChannelControllerProxySourceType">
    <xsd:sequence>
      <xsd:element name="CampaignServerCorbaRef" type="MultiCorbaObjectRefType"/>
      <xsd:element name="ProxyRefs" type="MultiCorbaObjectRefType" minOccurs="0"/>
    </xsd:sequence>
    <xsd:attribute name="use_local_on_first_load" type="xsd:boolean" default="true"/>
  </xsd:complexType>

  <xsd:complexType name="ChannelControllerColoSettingsType">
    <xsd:attribute name="colo" type="xsd:positiveInteger" use="required"/>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="ChannelServerGroupType">
    <xsd:sequence>
      <xsd:element name="ChannelServerHost"
        type="ChannelServerHostType"
        minOccurs="1"
        maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ChannelServerHostType">
    <xsd:sequence>
      <xsd:element name="ChannelServerGrpcRef"
        type="GrpcEndpointConfigType"
        minOccurs="1"
        maxOccurs="1"/>
      <xsd:element name="ChannelUpdateRef"
        type="CorbaObjectRefType"
        minOccurs="0"
        maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>
