<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.adintelligence.net/xsd/AdServer/Configuration"
  xmlns="http://www.adintelligence.net/xsd/AdServer/Configuration"
  elementFormDefault="qualified"
  xml:lang="en"
  version="1.0">

  <xsd:annotation>
    <xsd:documentation>
      ChannelController2 Configuration File XML Schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:include schemaLocation="../AdServerCommons/AdServerCommons.xsd"/>

  <xsd:element name="AdConfiguration" type="AdConfigurationType"/>

  <xsd:complexType name="AdConfigurationType">
    <xsd:sequence>
      <xsd:element name="ChannelController2Config"
        type="ChannelController2ConfigType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ChannelController2ConfigType">
    <xsd:sequence>
      <xsd:element name="GrpcConfig" type="GrpcConfigType">
        <xsd:annotation>
          <xsd:documentation>
            GrpcConfig for service
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element name="Logger" type="ErrorLoggerType">
        <xsd:annotation>
          <xsd:documentation>
            Error logger for ChannelController2
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element name="ChannelServerGroup"
        type="ChannelServerGroupType"
        minOccurs="1"
        maxOccurs="unbounded">
        <xsd:annotation>
          <xsd:documentation>
            ChannelServer gRPC endpoint group
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>

    <xsd:attribute name="count_chunks"
      type="xsd:positiveInteger"
      use="required"/>
  </xsd:complexType>

  <xsd:complexType name="ChannelServerGroupType">
    <xsd:sequence>
      <xsd:element name="ChannelServerHost"
        type="ChannelServerHostType"
        minOccurs="1"
        maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ChannelServerHostType">
    <xsd:sequence>
      <xsd:element name="ChannelServerGrpcRef"
        type="GrpcEndpointConfigType"
        minOccurs="1"
        maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>
