add_library(FrontendServerCommons
  FCGIAcceptor.cpp
  FCGIAcceptorStats.cpp
  Http2Acceptor.cpp
  WorkerStatsObject.cpp
)

target_link_libraries(FrontendServerCommons
  PRIVATE
    FCGI
    Commons
    Generics
    Logger
    Sync
    Boost::headers
    Nghttp2::Nghttp2
)

add_executable(FCGIServer
  FCGIServer.cpp
  FrontendsPool.cpp
)

target_link_libraries(FCGIServer
  PRIVATE
    PkgConfig::Jemalloc
    FCGIServerConfigXSD
    BiddingFrontend
    DirectoryModule
    PubPixelFrontend
    ContentFrontend
    WebStatFrontend
    ActionFrontend
    UserBindFrontend
    PassFrontend
    PassPixelFrontend
    OptoutFrontend
    AdInstFrontend
    ClickFrontend
    ImprTrackFrontend
    AdFrontend
    XMLUtility
    FrontendServerCommons
    CommonModule
    CampaignServerIDL
    ProcessControlIDL
    Commons
    CORBACommons
    HTTP
    HttpServer
    Generics
)

target_include_directories(FCGIServer PRIVATE
  ${CMAKE_BINARY_DIR}/CampaignSvcs/CampaignManager
  ${CMAKE_BINARY_DIR}/ChannelSvcs/ChannelServer
  ${CMAKE_BINARY_DIR}/UserInfoSvcs/UserBindServer
  ${CMAKE_BINARY_DIR}/UserInfoSvcs/UserInfoManager
  ${PB_DIRECTORY}/CampaignSvcs/CampaignManager
  ${PB_DIRECTORY}/ChannelSvcs/ChannelServer
  ${PB_DIRECTORY}/UserInfoSvcs/UserBindServer
  ${PB_DIRECTORY}/UserInfoSvcs/UserInfoManager
)
