news_item_server_port=10124
export news_item_server_port

news_query_server_port=10125
export news_query_server_port

news_cache_controller_port=10126
export news_cache_controller_port

word_net_pn_server_port=10131
export word_net_pn_server_port

sync_logs_port=10112
export sync_logs_port

stats_collector_port=10118
export stats_collector_port

user_info_manager_port=10101
export user_info_manager_port

user_info_manager_controller_port=10102
export user_info_manager_controller_port

