channel_server_port=10103
export channel_server_port

channel_controller_port=10104
export channel_controller_port

campaign_manager_port=10107
export campaign_manager_port

ad_frontend_port=10180
export ad_frontend_port

