add_subdirectory(BiddingFrontendRequestInfoFillerPerfTest)
add_subdirectory(BiddingFrontendLoggerPerfTest)
add_subdirectory(BiddingFrontendHashMapPerfTest)
add_subdirectory(BiddingFrontendCoreTest)
add_subdirectory(FastJsonParserTest)
add_subdirectory(FastJsonParserPerfTest)
add_subdirectory(PlatformMatcherTest)
