ADD_SUBDIRECTORY(BiddingFrontendRequestInfoFillerPerfTest)
ADD_SUBDIRECTORY(BiddingFrontendLoggerPerfTest)
ADD_SUBDIRECTORY(BiddingFrontendHashMapPerfTest)
ADD_SUBDIRECTORY(BiddingFrontendCoreTest)
ADD_SUBDIRECTORY(FastJsonParserTest)
ADD_SUBDIRECTORY(FastJsonParserPerfTest)
ADD_SUBDIRECTORY(PlatformMatcherTest)
