services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # TCP interface
      - "9009:9009"  # interface for interclaster
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse  # store data out of container
      - ./querys/clickhouse_create_table.sql:/docker-entrypoint-initdb.d/clickhouse_create_table.sql # init script

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # port Redis
    volumes:
      - ./redis_data:/data  # store data out of container