#ifndef BIDCOSTPREDICTOR_BIDCOSTPREDICTOR_IDL_HPP
#define BIDCOSTPREDICTOR_BIDCOSTPREDICTOR_IDL_HPP

#include <Commons/CorbaTypes.idl>

module PredictorSvcs
{
module BidCostPredictor
{

struct CostRequest
{
  unsigned long tag_id;
  string url;
  CORBACommons::DecimalInfo win_rate;
  CORBACommons::DecimalInfo current_cost;
};

struct CostResponse
{
  CORBACommons::DecimalInfo cost;
};

struct CtrRequest
{
  unsigned long tag_id;
  string url;
};

struct CtrResponse
{
  long clicks;
  long imps;
};

interface BidCostPredictorServer
{
  exception ImplementationException
  {
    string description;
  };

  CostResponse get_cost(in CostRequest) raises(ImplementationException);

  CtrResponse get_ctr(in CtrRequest) raises(ImplementationException);
};

}; // module PredictorSvcs
}; // module PredictorSvcs

#endif // BIDCOSTPREDICTOR_BIDCOSTPREDICTOR_IDL_HPP