add_subdirectory(UserBindAdmin)
add_subdirectory(UserBindController)
add_subdirectory(UserBindServer)
add_subdirectory(UserBindClient)
add_subdirectory(UserBindUtil)
add_subdirectory(UserInfoAdmin)
add_subdirectory(UserInfoCommons)
add_subdirectory(UserInfoManager)
add_subdirectory(UserInfoManagerProxy)
add_subdirectory(UserInfoManagerPlayer)
add_subdirectory(UserInfoClient)
add_subdirectory(UserInfoController)
