campaign_server_port=10106
export campaign_server_port

news_query_server_port=10125
export news_query_server_port

word_net_pn_server_port=10131
export word_net_pn_server_port

request_info_manager_port=10116
export request_info_manager_port

expression_matcher_port=10113
export expression_matcher_port

sync_logs_port=10112
export sync_logs_port

user_info_manager_port=10101
export user_info_manager_port

user_info_manager_controller_port=10102
export user_info_manager_controller_port

