channel_server_port=12403
export channel_server_port

channel_controller_port=12404
export channel_controller_port

channel_search_service_port=12115
export channel_search_service_port

campaign_manager_port=12407
export campaign_manager_port

ad_frontend_port=12480
export ad_frontend_port

