news_query_server_port=10125
export news_query_server_port

request_info_manager_port=10116
export request_info_manager_port

keyword_matcher_port=10108
export keyword_matcher_port

sync_logs_port=10112
export sync_logs_port

