add_library(ClickFrontend SHARED
  RequestInfoFiller.cpp
  ClickFrontend.cpp
)

target_link_libraries(ClickFrontend
  Stream
  Geoip
  CORBACommons
  Polyglot
  Commons
  ChannelManagerControllerIDL
  UserInfoManagerControllerIDL
  UserInfoClusterControlIDL
  DomainParser
  StatInfoIDL
  BillStatInfoIDL
  CampaignServerIDL
  UserBindServerIDL
  UserBindContainer
  UserBindClient
  RequestMatchers
  FrontendStatistic
  UserIdController
  CommonModule
  CampaignManagerClient
  FeConfigXSD
  FCGI
)
