campaign_server_port=12106
export campaign_server_port

news_item_server_port=10124
export news_item_server_port

news_query_server_port=10125
export news_query_server_port

news_cache_controller_port=10126
export news_cache_controller_port

user_info_manager_port=12101
export user_info_manager_port

user_info_manager_controller_port=12102
export user_info_manager_controller_port

log_generalizer_port=12111
export log_generalizer_port

request_info_manager_port=12116
export request_info_manager_port

expression_matcher_port=12113
export expression_matcher_port

keyword_matcher_port=10108
export keyword_matcher_port

sync_logs_port=12112
export sync_logs_port

