add_subdirectory(AdServerCommons)
add_subdirectory(CampaignSvcs)
add_subdirectory(ChannelSearchSvcs)
add_subdirectory(ChannelSvcs)
add_subdirectory(Controlling)
add_subdirectory(Frontends)
add_subdirectory(LogProcessing)
add_subdirectory(Predictor)
add_subdirectory(RequestInfoSvcs)
add_subdirectory(UserInfoSvcs)
add_subdirectory(Utils)
add_subdirectory(tests)
