edition = "2023";

option features.field_presence = IMPLICIT;
option features.enum_type = OPEN;
option features.repeated_field_encoding = PACKED;
option features.utf8_validation = NONE;
option features.json_format = ALLOW;

package adserver.grpc;

service BatchTransport {
  rpc stream_batches(stream BatchRequest) returns (stream BatchResponse);
}

message BatchRequestItem {
  uint64 request_id = 1;
  string full_method = 2;
  bytes payload = 3;
}

message BatchRequest {
  repeated BatchRequestItem items = 1;
  uint64 batch_id = 2;
  repeated uint32 response_time_steps_us = 3;
}

message BatchResponseItem {
  uint64 request_id = 1;
  int32 status_code = 2;
  string status_message = 3;
  bytes payload = 4;
}

message BatchResponse {
  repeated BatchResponseItem items = 1;
  uint64 batch_id = 2;
}
