edition = "2023";

option features.field_presence = IMPLICIT;
option features.enum_type = OPEN;
option features.repeated_field_encoding = PACKED;
option features.utf8_validation = NONE;
option features.json_format = ALLOW;

package adserver.grpc.process_control;

service ProcessControl {
  rpc get_status(GetStatusRequest) returns (GetStatusResponse);
  rpc get_db_state(GetDbStateRequest) returns (GetDbStateResponse);
  rpc set_db_state(SetDbStateRequest) returns (SetDbStateResponse);
}

message GetStatusRequest {}

message GetStatusResponse {
  bool ready = 1;
  string description = 2;
}

message GetDbStateRequest {}

message GetDbStateResponse {
  bool enabled = 1;
}

message SetDbStateRequest {
  bool enabled = 1;
}

message SetDbStateResponse {}
