edition = "2023";

option features.field_presence = IMPLICIT;
option features.enum_type = OPEN;
option features.repeated_field_encoding = PACKED;
option features.utf8_validation = NONE;
option features.json_format = ALLOW;

package adserver.channel_svcs.channel_server;

service ChannelServerGrpc {
  rpc match(MatchRequest) returns (MatchResponse);
  rpc get_ccg_traits(GetCcgTraitsRequest) returns (GetCcgTraitsResponse);
  rpc check_configuration(CheckConfigurationRequest)
    returns (CheckConfigurationResponse);
  rpc set_sources(SetSourcesRequest) returns (SetSourcesResponse);
  rpc set_proxy_sources(SetProxySourcesRequest) returns (SetProxySourcesResponse);
}

message ChannelAtom {
  uint64 id = 1;
  uint64 trigger_channel_id = 2;
}

message TriggerMatchResult {
  repeated ChannelAtom page_channels = 1;
  repeated ChannelAtom search_channels = 2;
  repeated ChannelAtom url_channels = 3;
  repeated ChannelAtom url_keyword_channels = 4;
  repeated uint64 uid_channels = 5;
}

message ContentChannelAtom {
  uint64 id = 1;
  uint64 weight = 2;
}

message MatchRequest {
  string request_id = 1;
  string first_url = 2;
  string first_url_words = 3;
  string urls = 4;
  string urls_words = 5;
  string pwords = 6;
  string swords = 7;
  bytes uid = 8;
  string statuses = 9;
  bool non_strict_word_match = 10;
  bool non_strict_url_match = 11;
  bool return_negative = 12;
  bool simplify_page = 13;
  bool fill_content = 14;
}

message MatchResponse {
  TriggerMatchResult matched_channels = 1;
  repeated ContentChannelAtom content_channels = 2;
  bool no_adv = 3;
  bool no_track = 4;
  bytes match_time = 5;
  string hostname = 6;
  bool full_loaded = 7;
}

message GetCcgTraitsRequest {
  repeated uint64 ids = 1;
}

message CcgKeyword {
  uint64 ccg_keyword_id = 1;
  uint64 ccg_id = 2;
  uint64 channel_id = 3;
  bytes max_cpc = 4;
  bytes ctr = 5;
  string click_url = 6;
  string original_keyword = 7;
}

message GetCcgTraitsResponse {
  repeated CcgKeyword ccg_keywords = 1;
  repeated uint64 neg_ccg = 2;
  string hostname = 3;
}

message CheckConfigurationRequest {}

message CheckConfigurationResponse {
  uint64 check_sum = 1;
}

message SetSourcesRequest {
  repeated string campaign_refs = 1;
  string pg_connection = 2;
  uint64 count_chunks = 3;
  uint64 colo = 4;
  string version = 5;
  uint64 check_sum = 6;
  repeated uint64 sources = 7;
}

message SetSourcesResponse {}

message LocalLoadServer {
  string channel_update_ref = 1;
  repeated uint64 sources = 2;
  uint64 count_chunks = 3;
}

message LocalLoadGroup {
  repeated LocalLoadServer servers = 1;
}

message SetProxySourcesRequest {
  repeated string campaign_refs = 1;
  repeated string proxy_refs = 2;
  repeated LocalLoadGroup local_groups = 3;
  uint64 count_chunks = 4;
  uint64 colo = 5;
  string version = 6;
  uint64 check_sum = 7;
  repeated uint64 sources = 8;
}

message SetProxySourcesResponse {}
