name: ci_rtbserver_build

on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rtb repository
        uses: actions/checkout@v3
    
      - name: Checkout unixcomms repository
        uses: actions/checkout@v3
        with:
          repository: yoori/unixcommons_cobrazz.git
          ref: main
          
      - name: Set up Docker Compose
        run: |
          sudo apt install docker-compose
          
      - name: Making base cache
        working-directory: rtbserver_cobrazz/ci
        run: |
          pwd
          sh envprep.sh
          exit $?
          
      - name: build
        working-directory: ci
        run: |
          docker-compose run build;
          exit $?;